# Generated by Django 4.2.7 on 2023-11-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_details_student_details_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='Roll_no',
            field=models.IntegerField(default=0),
        ),
    ]
