# Generated by Django 4.2.7 on 2023-11-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student_details_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_details',
            name='Phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student_details',
            name='Age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='Roll_no',
            field=models.IntegerField(default=1),
        ),
    ]
