# Generated by Django 4.2.7 on 2023-11-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_student_details_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='Roll_no',
            field=models.IntegerField(default=0),
        ),
    ]
