# Generated by Django 4.2.7 on 2023-11-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_student_details_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_details',
            name='Phone',
            field=models.CharField(max_length=12),
        ),
    ]
