# Generated by Django 4.2.7 on 2023-11-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_contact_details_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='Age',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='Roll_no',
            field=models.CharField(max_length=12),
        ),
    ]
